B4J=true
Group=Handlers
ModulesStructureVersion=1
Type=Class
Version=10.2
@EndOfDesignText@
'Handler class
Sub Class_Globals
	Private Response As ServletResponse
	Private Method As String
End Sub

Public Sub Initialize

End Sub

Sub Handle (req As ServletRequest, resp As ServletResponse)
	Response = resp
	Method = req.Method.ToUpperCase
	Dim path As String = req.RequestURI
	If path = "/" Then
		If Method = "GET" Then
			ShowIndexPage
			Return
		End If
	Else If path = "/modal" Then
		If Method = "POST" Then
			Response.Write(GenerateModal)
			Return
		End If
		Response.SendError(405, "<h1>405 Method Not Allowed</h1>")
		Return
	End If
	Response.SendError(404, "<h1>404 Page Not Found</h1>")
End Sub

Private Sub ShowIndexPage
	Dim doc As MiniHtml
	doc.Initialize("")
	doc.Write("<!DOCTYPE html>")
	doc.Write(GeneratePage)
	Response.Write(doc.ToString)
End Sub

Sub Div As MiniHtml
	Return CreateTag("div")
End Sub

Sub Meta As MiniHtml
	Return CreateTag("meta")
End Sub

Sub CreateTag (Name As String) As MiniHtml
	Dim tag1 As MiniHtml
	tag1.Initialize(Name)
	Return tag1
End Sub

Public Sub GeneratePage As String
    Dim html1 As MiniHtml = CreateTag("html")
    html1.lang("en")
    html1.comment2(" Generated by MiniHTML2 ", True)
    Dim head1 As MiniHtml = CreateTag("head").up(html1)
    Dim meta1 As MiniHtml = Meta.up(head1)
    meta1.attr("charset", "UTF-8")
    Dim meta2 As MiniHtml = Meta.up(head1)
    meta2.attr("name", "viewport")
    meta2.attr("content", "width=device-width, initial-scale=1")
    Dim title1 As MiniHtml = CreateTag("title").up(head1)
    title1.text("MiniHtml2 Demo")
    head1.cdn2("style", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css", "", "")
    head1.cdn2("script", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js", "", "")
    head1.cdn2("script", "https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js", "", "")
    Dim body1 As MiniHtml = CreateTag("body").up(html1)
    Dim div1 As MiniHtml = Div.up(body1)
    div1.cls("d-flex align-items-center")
    div1.sty("height: 100vh")
    Dim div2 As MiniHtml = Div.up(div1)
    div2.sty("margin: auto")
    Dim div3 As MiniHtml = Div.up(div2)
    div3.attr("id", "modals-here")
    div3.cls("modal modal-blur fade")
    div3.sty("display: none")
    div3.attr("aria-hidden", "false")
    div3.attr("tabindex", "-1")
    div3.FormatAttributes = True
    Dim div4 As MiniHtml = Div.up(div3)
    div4.cls("modal-dialog modal-lg modal-dialog-centered")
    div4.attr("role", "document")
    Dim div5 As MiniHtml = Div.up(div4)
    div5.cls("modal-content")
    Dim button1 As MiniHtml = CreateTag("button").up(div2)
    button1.attr("hx-post", "/modal")
    button1.attr("hx-target", "#modals-here")
    button1.attr("hx-trigger", "click")
    button1.attr("data-bs-toggle", "modal")
    button1.attr("data-bs-target", "#modals-here")
    button1.cls("btn btn-primary text-uppercase")
    button1.text("Open Modal")
    button1.FormatAttributes = True
	button1.multiline
    Return html1.build
End Sub

Sub GenerateModal As String
    Dim div1 As MiniHtml = Div
    div1.cls("modal-dialog modal-lg modal-dialog-centered")
    Dim div2 As MiniHtml = Div.up(div1)
    div2.cls("modal-content")
    Dim div3 As MiniHtml = Div.up(div2)
    div3.cls("modal-header")
    Dim h51 As MiniHtml = CreateTag("h5").up(div3)
    h51.cls("modal-title")
    h51.text("Modal title")
    Dim div4 As MiniHtml = Div.up(div2)
    div4.cls("modal-body")
    Dim p1 As MiniHtml = CreateTag("p").up(div4)
    p1.text("Modal body text goes here.")
    Dim div5 As MiniHtml = Div.up(div2)
    div5.cls("modal-footer")
    Dim button1 As MiniHtml = CreateTag("button").up(div5)
    button1.attr("type", "button")
    button1.cls("btn btn-secondary text-uppercase")
    button1.attr("data-bs-dismiss", "modal")
    button1.text("Close")
    Return div1.Build
End Sub